/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 test3.gltf -t
*/

import * as THREE from "three";
import React, { Suspense, useRef } from "react";
import { Image, PerspectiveCamera, RenderTexture, Text, useGLTF, useTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";

function Foo() {
  // images
  const map = useTexture(["imgs/event1.jpeg", "imgs/wow.webp", "imgs/galaxy.jpeg", "imgs/event2.jpeg", "imgs/event3.jpeg", "imgs/event5.jpeg"]);

  // videos
  // const arr = [
  //   useVideoTexture("videos/vid1.mp4"),
  //   useVideoTexture("videos/vid2.mp4"),
  //   useVideoTexture("videos/vid3.mp4"),
  //   useVideoTexture("videos/vid4.mp4"),
  //   useVideoTexture("videos/vid5.mp4"),
  //   useVideoTexture("videos/vid6.mp4"),
  // ];
  return (
    <>
      {map.map((texture, idx) => (
        <meshBasicMaterial key={texture.id} attach={`material-${idx}`} map={texture} />
      ))}
    </>
  );
}
