/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 nice.gltf
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export const Nice = (props) => {
  const { nodes, materials } = useGLTF("/nice.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Circle.geometry} material={materials["Material.001"]} scale={2.22} />
    </group>
  );
};

useGLTF.preload("/nice.gltf");
