/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 test1.gltf -t
*/

import * as THREE from "three";
import React, { Suspense, useRef } from "react";
import { RenderTexture, Text, useGLTF, useTexture, useVideoTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Circle: THREE.Mesh;
  };
  materials: {
    ["Material.001"]: THREE.MeshStandardMaterial;
  };
};

export function Test1(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/blender/test1.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Circle.geometry} material={materials["Material.001"]}>
        <meshStandardMaterial>
          <RenderTexture attach="map">
            <color attach="background" args={["pink"]} />
            <Text>hello</Text>
          </RenderTexture>
        </meshStandardMaterial>
        {/* <Suspense fallback={null}>
          <Foo />
        </Suspense> */}
      </mesh>
    </group>
  );
}

useGLTF.preload("/blender/test1.gltf");

function Foo() {
  // images
  const map = useTexture(["imgs/event1.jpeg", "imgs/wow.webp", "imgs/galaxy.jpeg", "imgs/event2.jpeg", "imgs/event3.jpeg", "imgs/event5.jpeg"]);

  // videos
  const arr = [
    useVideoTexture("videos/vid1.mp4"),
    useVideoTexture("videos/vid2.mp4"),
    useVideoTexture("videos/vid3.mp4"),
    useVideoTexture("videos/vid4.mp4"),
    useVideoTexture("videos/vid5.mp4"),
    useVideoTexture("videos/vid6.mp4"),
  ];
  return (
    <>
      {map.map((texture, idx) => (
        <meshBasicMaterial key={texture.id} attach={`material-${idx}`} map={texture} side={THREE.TwoPassDoubleSide} />
      ))}
    </>
  );
}
