/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Circle: THREE.Mesh;
  };
  materials: {
    ["Material.001"]: THREE.MeshStandardMaterial;
  };
};

export function NiceModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/blender/wgltf.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Circle.geometry} material={materials["Material.001"]} scale={2.22} />
    </group>
  );
}

useGLTF.preload("/blender/wgltf.glb");
